package com.example.ajedrez.View.Students;

import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.v4.app.Fragment;
import android.support.v7.widget.AppCompatEditText;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.example.ajedrez.Model.Student;
import com.example.ajedrez.R;
import com.example.ajedrez.Utils.GenericMethodsManager;
import com.example.ajedrez.View.MainActivity;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

/**
 * A simple {@link Fragment} subclass.
 * Activities that contain this fragment must implement the
 * {@link NewStudentListener} interface
 * to handle interaction events.
 * Use the {@link NewStudentFragment#newInstance} factory method to
 * create an instance of this fragment.
 */
public class NewStudentFragment extends Fragment {

    private Student newStudent =  new Student();
    private NewStudentListener mListener;

    public void setListener(MainActivity activity) {
        this.mListener = activity;
    }

    public static NewStudentFragment newInstance() {
        return new NewStudentFragment();
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_new_student, container, false);
        FloatingActionButton add = view.findViewById(R.id.saveStudent);
        add.setOnClickListener(v -> createUser());
        AppCompatEditText nameText = view.findViewById(R.id.nameText);
        nameText.addTextChangedListener(new TextWatcher() {
            public void afterTextChanged(Editable s) {
                newStudent.setName(s.toString());
            }
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {}
            public void onTextChanged(CharSequence s, int start, int before, int count) {}
        });

        AppCompatEditText phoneNumberText = view.findViewById(R.id.phoneText);
        phoneNumberText.addTextChangedListener(new TextWatcher() {
            public void afterTextChanged(Editable s) {
                newStudent.setPhoneNumber(s.toString());
            }
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {}
            public void onTextChanged(CharSequence s, int start, int before, int count) {}
        });

        AppCompatEditText birthDateText = view.findViewById(R.id.birthDateText);
        birthDateText.setOnClickListener(v ->
                GenericMethodsManager.getInstance().openCalendar(birthDateText, getContext()));
        birthDateText.addTextChangedListener(new TextWatcher() {
            public void afterTextChanged(Editable s) {
                newStudent.setBirthDay(s.toString());
            }
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {}
            public void onTextChanged(CharSequence s, int start, int before, int count) {}
        });

        AppCompatEditText schoolText = view.findViewById(R.id.schoolText);
        schoolText.addTextChangedListener(new TextWatcher() {
            public void afterTextChanged(Editable s) {
                newStudent.setSchool(s.toString());
            }
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {}
            public void onTextChanged(CharSequence s, int start, int before, int count) {}
        });

        String autoGeneratedDate = GenericMethodsManager.getInstance().getSimpleDate();
        AppCompatEditText firstClassText = view.findViewById(R.id.firstClassText);
        firstClassText.setText(autoGeneratedDate);
        newStudent.setStartingDate(autoGeneratedDate);
        newStudent.setLastClass(autoGeneratedDate);
        firstClassText.setOnClickListener(v ->
                GenericMethodsManager.getInstance().openCalendar(firstClassText, getContext()));
        firstClassText.addTextChangedListener(new TextWatcher() {
            public void afterTextChanged(Editable s) {
                newStudent.setStartingDate(s.toString());
                newStudent.setLastClass(s.toString());
            }
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {}
            public void onTextChanged(CharSequence s, int start, int before, int count) {}
        });

        return view;
    }

    private void createUser(){
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        DatabaseReference myRef = database.getReference("students");
        myRef.push().setValue(newStudent);
        mListener.onStudentCreated();
    }

    public interface NewStudentListener {
        void onStudentCreated();
    }
}
